version: '3.9'

services:
  ppostgres:
    container_name: ppostgres
    image: "postgres:14-alpine"
    restart: unless-stopped
    ports:
      - "127.0.0.1:5432:5432"
    environment:
      POSTGRES_PASSWORD: $PPOSTGRES_PASSWORD
      POSTGRES_USER: ${PPOSTGRES_USER:-$USER}
      POSTGRES_DB: ${PPOSTGRES_USER:-$USER}
    volumes:
      - "ppostgres-data:/var/lib/postgresql/data:rw"

volumes:
  ppostgres-data:
